# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Ejecucion test con Selenium

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  checks: write

jobs:
  run-test:

   strategy:
     matrix:
      os: [ubuntu-latest, windows-latest]
      driver: [chrome, firefox]
      window-size: [1334x750, 1920x1080]
      tags: ["@sauceDemo"]
      exclude:
      - os: windows-latest
        driver: safari
      - os: windows-latest
        driver: firefox
      - os: ubuntu-latest
        driver: safari
      - os: ubuntu-latest
        driver: chrome

   name: System= ${{matrix.os}} -- Driver= ${{matrix.driver}} -- Window-size = ${{matrix.window-size}}
   runs-on: ${{matrix.os}}

   steps:
   - name: repo
     uses: actions/checkout@v3
   - name: Set up JDK 17
     uses: actions/setup-java@v3
     with:
       java-version: '17'
       distribution: 'temurin'
       gradle-version: '8.1.1'
   - name: Run test with chrome driver
     run: |
      if ${{ matrix.os }} == "windows-latest"; then
      gradlew.bat test -Dcucumber.filter.tags="${{matrix.tags}}" -DwebDriver=${{matrix.driver}} -DheadlessMode=true -DwindowSize=${{matrix.window-size}} --info
      else
      gradle test -Dcucumber.filter.tags="${{matrix.tags}}" -DwebDriver=${{matrix.driver}} -DheadlessMode=true -DwindowSize=${{matrix.window-size}} --info
      fi
     shell: bash

   - name: upload artifact
     uses: actions/upload-artifact@v3
     with:
        name: html report Tags= ${{matrix.tags}} - System= ${{matrix.os}} - ${{matrix.driver}} - window-size = ${{matrix.window-size}}
        path: Test-reports/
     if: always()

   - name: Publish cucumber report
     uses: deblockt/cucumber-report-annotations-action@v1.7
     with:
        name: Cucumber report Tags= ${{matrix.tags}} - System= ${{matrix.os}} - driver= ${{matrix.driver}} - window-size = ${{matrix.window-size}}
        access-token: ${{ secrets.GITHUB_TOKEN }}
        path: "report/cucumber-report/cucumber.json"
     if: always()